---
title: "Data Import"
output: github.document
---

```{r, echo=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```


##Data Import: CSVs

Let's import data using the `readr` package.

```{r}
litters.df = read.csv("./data_import_examples/FAS_litters.csv")
litters.df = janitor::clean_names(litters.df)
```

look at the data

```{r}
litters.df

head(litters.df)
tail(litters.df)
```

```{r}
skimr::skim(litters.df)
```

`read_csv` options ..
```{r}
read.csv("./data_import_examples/FAS_litters.csv", skip=10, col_names = FALSE)
```

##Other File Formats
We need to read in an excel spreadsheet

```{r}
mlb.df=read_excel("./data_import_examples/mlb11.xlsx")

```
```{r, eval=FALSE}
view(mlb.df)
```

```{r}
lotr.words.df=read_excel("./data_import_examples/LotR_Words.xlsx", range="B3:D6")
```

##Still more formats...

Read in a SAS dataset..

```{r}
pulse.df = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
view(pulse.df)
```


##Data Export

```{r}
write_csv(lotr.words.df, file="./lotr.words.df.csv")
```

##Why not base r??
```{r}
dont_do_this_df = read.csv("./data_import_examples/FAS_litters.csv")

#don't use read.csv (base R), use read_csv
```



